# This file was auto-generated by Fern from our API Definition.

"""
jsonable_encoder converts a Python object to a JSON-friendly dict
(e.g. datetimes to strings, Pydantic models to dicts).

Taken from FastAPI, and made a bit simpler
https://github.com/tiangolo/fastapi/blob/master/fastapi/encoders.py
"""

import base64
import dataclasses
import datetime as dt
from enum import Enum
from pathlib import PurePath
from types import GeneratorType
from typing import Any, Callable, Dict, List, Optional, Set, Union

import pydantic
from .datetime_utils import serialize_datetime
from .pydantic_utilities import (
    IS_PYDANTIC_V2,
    encode_by_type,
    to_jsonable_with_fallback,
)

SetIntStr = Set[Union[int, str]]
DictIntStrAny = Dict[Union[int, str], Any]


def jsonable_encoder(obj: Any, custom_encoder: Optional[Dict[Any, Callable[[Any], Any]]] = None) -> Any:
    # Fast-path for primitive types
    if isinstance(obj, (str, int, float, type(None))):
        return obj
    # Explicitly check bytes for b64encoding
    if isinstance(obj, bytes):
        return base64.b64encode(obj).decode("utf-8")
    # Short-circuit Enum (most are primitive types, but faster than below path in profiling)
    if isinstance(obj, Enum):
        return obj.value
    # Short-circuit pathlib PurePath
    if isinstance(obj, PurePath):
        return str(obj)
    # Handle datetime fast-path
    if isinstance(obj, dt.datetime):
        return serialize_datetime(obj)
    if isinstance(obj, dt.date):
        return str(obj)
    # Custom encoder - fast check and O(1) check before param sweeps
    custom_encoder = custom_encoder or {}
    t = type(obj)
    if t in custom_encoder:
        return custom_encoder[t](obj)
    for encoder_type, encoder_instance in custom_encoder.items():
        if isinstance(obj, encoder_type):
            return encoder_instance(obj)
    # Pydantic models
    if isinstance(obj, pydantic.BaseModel):
        if IS_PYDANTIC_V2:
            encoder = getattr(obj.model_config, "json_encoders", {}).copy()  # type: ignore # Pydantic v2
        else:
            encoder = getattr(obj.__config__, "json_encoders", {}).copy()  # type: ignore # Pydantic v1
        if custom_encoder:
            encoder.update(custom_encoder)
        obj_dict = obj.dict(by_alias=True)
        if "__root__" in obj_dict:
            obj_dict = obj_dict["__root__"]
        if "root" in obj_dict:
            obj_dict = obj_dict["root"]
        return jsonable_encoder(obj_dict, custom_encoder=encoder)
    # Dataclasses - prefer asdict (fast for deep trees)
    if dataclasses.is_dataclass(obj):
        return jsonable_encoder(dataclasses.asdict(obj), custom_encoder=custom_encoder)
    # Dict encoding via dict comprehension
    if isinstance(obj, dict):
        return {
            jsonable_encoder(k, custom_encoder=custom_encoder): jsonable_encoder(v, custom_encoder=custom_encoder)
            for k, v in obj.items()
        }
    # Sequence types encoded with list comprehension
    if isinstance(obj, (list, set, frozenset, GeneratorType, tuple)):
        return [jsonable_encoder(item, custom_encoder=custom_encoder) for item in obj]

    def fallback_serializer(o: Any) -> Any:
        attempt_encode = encode_by_type(o)
        if attempt_encode is not None:
            return attempt_encode

        try:
            data = dict(o)
        except Exception as e:
            errors: List[Exception] = []
            errors.append(e)
            try:
                data = vars(o)
            except Exception as e:
                errors.append(e)
                raise ValueError(errors) from e
        return jsonable_encoder(data, custom_encoder=custom_encoder)

    return to_jsonable_with_fallback(obj, fallback_serializer)
