# This file was auto-generated by Fern from our API Definition.

from typing import Any, Dict, List, Optional, Tuple

import pydantic


# Flattens dicts to be of the form {"key[subkey][subkey2]": value} where value is not a dict
def traverse_query_dict(dict_flat: Dict[str, Any], key_prefix: Optional[str] = None) -> List[Tuple[str, Any]]:
    result = []
    append = result.append
    extend = result.extend
    # Cache isinstance for dict and list for speed
    dict_type = dict
    list_type = list
    for k, v in dict_flat.items():
        key = f"{key_prefix}[{k}]" if key_prefix is not None else k
        if isinstance(v, dict_type):
            extend(traverse_query_dict(v, key))
        elif isinstance(v, list_type):
            # Avoid repeated isinstance(arr_v, dict) calls when possible
            for arr_v in v:
                if isinstance(arr_v, dict_type):
                    extend(traverse_query_dict(arr_v, key))
                else:
                    append((key, arr_v))
        else:
            append((key, v))
    return result


def single_query_encoder(query_key: str, query_value: Any) -> List[Tuple[str, Any]]:
    BaseModel = pydantic.BaseModel
    dict_type = dict
    list_type = list
    # Avoid repeating isinstance twice
    if isinstance(query_value, BaseModel):
        obj_dict = query_value.dict(by_alias=True)
        return traverse_query_dict(obj_dict, query_key)
    elif isinstance(query_value, dict_type):
        return traverse_query_dict(query_value, query_key)
    elif isinstance(query_value, list_type):
        encoded_values: List[Tuple[str, Any]] = []
        append = encoded_values.append
        extend = encoded_values.extend
        for value in query_value:
            if isinstance(value, BaseModel):
                obj_dict = value.dict(by_alias=True)
                extend(single_query_encoder(query_key, obj_dict))
            elif isinstance(value, dict_type):
                extend(single_query_encoder(query_key, value))
            else:
                append((query_key, value))
        return encoded_values
    return [(query_key, query_value)]


def encode_query(query: Optional[Dict[str, Any]]) -> Optional[List[Tuple[str, Any]]]:
    if query is None:
        return None

    encoded_query = []
    for k, v in query.items():
        encoded_query.extend(single_query_encoder(k, v))
    return encoded_query
